# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # https://developer.hashicorp.com/vagrant/docs

  # recommended providers:
  #   intel (amd64) CPU (mac/win/linux): virtualbox
  #   arm (arm64) CPU (mac): parallels

  config.vm.box = "wesdemos/ubuntu2310-arm"
  # config.vm.box_version = "1.1.3"
  #   arm64: parallels
  #     recommended for arm macs
  #   https://app.vagrantup.com/wesdemos/boxes/ubuntu2310-arm
  #
  # config.vm.box = "generic/ubuntu2310"
  #   amd64: parallels/vmware/virtualbox/hyperv/libvirt/qemu
  #   https://app.vagrantup.com/generic/boxes/ubuntu2310
  #
  # config.vm.box = "bento/ubuntu-23.10"
  #   amd64: parallels/vmware/virtualbox
  #   arm64: parallels/vmware
  #   https://app.vagrantup.com/bento/boxes/ubuntu-23.10
  #   TODO when course done, set as default box given both arm/intel support
  #
  # config.vm.box = "ubuntu/mantic64"
  #   amd64: virtualbox
  #   https://app.vagrantup.com/ubuntu/boxes/mantic64
  #


  config.vm.hostname = "ubuntu"

  # optional, tools and dotfiles:
  config.vm.provision "shell", name: "tools", path: "provision/tools.sh"

  # optional, shell startup files:
  config.vm.provision "file", source: "../shared/shell/config.fish", destination: "/home/vagrant/.config/fish/config.fish"
  config.vm.provision "file", source: "../shared/shell/.bashrc.mods", destination: "/home/vagrant/.bashrc.mods"

  # optional, install docker on vagrant up:
  # config.vm.provision "shell", name: "get-docker", path: "../shared/get-docker.sh"

  # host-only nic
  config.vm.network "private_network", ip: "192.168.33.10"





  # *** provider (hypervisor) specific settings ***
  # vagrant up --provider=parallels
  config.vm.provider "parallels" do |h|
    # https://parallels.github.io/vagrant-parallels/docs/configuration.html
    # h.gui = true
    h.memory = "8192"
    h.cpus = "6"
  end

  # vagrant up --provider=virtualbox
  config.vm.provider "virtualbox" do |h|
    # https://developer.hashicorp.com/vagrant/docs/providers/virtualbox/configuration
    # h.gui = true
    h.memory = "4096"
    h.cpus = "2"
  end

  # etc:
  # vmware: https://developer.hashicorp.com/vagrant/docs/providers/vmware/configuration
  # hyperv: https://developer.hashicorp.com/vagrant/docs/providers/hyperv/configuration


  # *** box update check ***
  # config.vm.box_check_update = false # disable
  # instead:   vagrant box update --box org/box


  # *** shared folders ***
  # disable shared folder (if encounter problems, i.e. parallels tools not installed into guest):
  # config.vm.synced_folder ".", "/vagrant", disabled: true


end
