# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = RbConfig::CONFIG["host_cpu"] == "arm64" ? "wesdemos/debian12-arm" : "generic/debian12"
  # ** see `debian` Vagrantfile for alternative box options **

  config.vm.hostname = "updates"



  # (optional) tools
  config.vm.provision "shell", name: "tools", path: "../ubuntu/provision/tools.sh"
  config.vm.provision "file", source: "../shared/shell/config.fish", destination: "/home/vagrant/.config/fish/config.fish"
  config.vm.provision "file", source: "../shared/shell/.bashrc.mods", destination: "/home/vagrant/.bashrc.mods"



  # UPDATE SCRIPTS
  config.vm.provision "shell", name: "install", path: "./scripts/1-install.sh"
  config.vm.provision "shell", name: "live-restore", path: "./scripts/1b-live-restore.sh"
  config.vm.provision "shell", name: "containers", path: "./scripts/2-containers.sh"
  # config.vm.provision "shell", name: "newer", path: "./scripts/3-newer.sh"
  config.vm.provision "shell", name: "latest", path: "./scripts/4-latest.sh"
  # run: once (default), always, never
  #   never == manually only (i.e. vagrant provision --provision-with 3-newer)
  # reset: true (reset communicator, i.e. ssh)




  # host-only nic
  config.vm.network "private_network", ip: "192.168.33.40"





  # *** provider (hypervisor) specific settings ***
  # vagrant up --provider=parallels
  config.vm.provider "parallels" do |h|
    # https://parallels.github.io/vagrant-parallels/docs/configuration.html
    # h.gui = true
    h.memory = "8192"
    h.cpus = "6"
  end

  # vagrant up --provider=virtualbox
  config.vm.provider "virtualbox" do |h|
    # https://developer.hashicorp.com/vagrant/docs/providers/virtualbox/configuration
    # h.gui = true
    h.memory = "4096"
    h.cpus = "2"
  end

  # etc:
  # vmware: https://developer.hashicorp.com/vagrant/docs/providers/vmware/configuration
  # hyperv: https://developer.hashicorp.com/vagrant/docs/providers/hyperv/configuration


  # *** box update check ***
  # config.vm.box_check_update = false # disable
  # instead:   vagrant box update --box org/box


  # *** shared folders ***
  # disable shared folder (if encounter problems, i.e. parallels tools not installed into guest):
  # config.vm.synced_folder ".", "/vagrant", disabled: true


end
